"""update blood request model

Revision ID: de544d911daa
Revises: 74e5f1ddc7f2
Create Date: 2026-06-29 08:27:00.744557

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'de544d911daa'
down_revision = '74e5f1ddc7f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blood_requests', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_hospital'), type_='foreignkey')
        batch_op.drop_column('hospital_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blood_requests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hospital_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_hospital'), 'hospitals', ['hospital_id'], ['id'])

    # ### end Alembic commands ###
